# ~/.config/tmux-sessionizer/tmux-sessionizer.conf
# Bash array syntax (sourced by tmux-sessionizer script)

TS_SEARCH_PATHS=(~/ ~/Documents/Projects)
TS_EXTRA_SEARCH_PATHS=(~/.config:2)
TS_MAX_DEPTH=2
# TS_SESSION_COMMANDS=()
# TS_LOG=true
