# Generated by esetup (scripts/apply-toolchain-env.sh). Do not edit by hand:
# it is rewritten wholesale. Re-run that script after installing or removing
# a toolchain, and commit the result.

# .NET SDK. `dotnet` runs without this; IDEs and language servers use it to
# find the SDK.
set -gx DOTNET_ROOT "/opt/homebrew/opt/dotnet/libexec"

# Google Cloud SDK. Puts components installed via `gcloud components install`
# on PATH; gcloud/gsutil/bq are already linked into the brew prefix. The include
# guards against duplicate PATH entries itself.
if test -f /opt/homebrew/share/google-cloud-sdk/path.fish.inc
  source /opt/homebrew/share/google-cloud-sdk/path.fish.inc
end

# Versioned .NET SDK kegs. Keg-only, deliberately not on PATH — the brew
# prefix's `dotnet` always wins there, so each gets a function instead.
function dotnet8 --description 'dotnet from the dotnet@8 keg'
  /opt/homebrew/opt/dotnet@8/bin/dotnet $argv
end
